import { supabase } from './supabase.js';
import { subscribeRoom, unsubscribeRoom } from './realtime.js';
import { PLAYERS } from '../data/players.js';
import { money, runMatchSimulation, pick } from './engine.js';

let s={id:null,room:null,players:[],channel:null,local:false};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const me=()=>window.__MA?.state?.user?.id||'local-user';
const meName=()=>window.__MA?.state?.profile?.username||'You';
const toast=(m,t)=>window.__MA.toast(m,t);
const clone=x=>JSON.parse(JSON.stringify(x));

async function load(){if(!s.id||!supabase)return;if(s.local)return;const [r,p]=await Promise.all([supabase.from('rooms').select('*').eq('id',s.id).single(),supabase.from('room_players').select('*').eq('room_id',s.id).order('seat')]);if(r.error)throw r.error;s.room=r.data;s.players=p.data||[];}
async function open(id){if(s.channel)unsubscribeRoom(s.channel);s.id=id;await load();if(!s.local&&supabase){s.channel=subscribeRoom(id,async()=>{try{await load();window.__MA.render()}catch(e){console.warn(e)}})}}
function localCreate(game,max,settings){const code=Math.random().toString(36).slice(2,8).toUpperCase();s={id:`local-${code}`,room:{id:`local-${code}`,code,game_type:game,max_players:Number(max),host_id:me(),status:'lobby',settings,game_state:{}},players:[{room_id:`local-${code}`,user_id:me(),seat:0,username:meName(),ready:false,team:0}],channel:null,local:true}}
function currentMe(){return s.players.find(p=>p.user_id===me())}
function startState(game,players,settings){
  if(game==='auction'){
    const count=Number(settings?.auctionCount||5);const budget=count===11?250000000:100000000;const pool=PLAYERS.slice().sort(()=>Math.random()-.5).slice(0,count).map(p=>({...p,startBid:Math.max(1000000,Math.round(((p.rating-70)*650000+Math.random()*1600000)/100000)*100000)}));
    return {phase:'auction',count,budget,currentIndex:0,currentBid:pool[0]?.startBid||1000000,highestSeat:null,players:pool,teams:Array.from({length:players},()=>({budget,players:[],coach:null})),lastCompensation:null,lastWinner:null};
  }
  if(game==='lebes')return {phase:'boxes',turnSeat:0,boxes:Array.from({length:6},(_,i)=>({i,playerId:pick(PLAYERS).id})),cards:Array.from({length:players},()=>[])};
  return {phase:'match',result:null};
}
async function rpc(name,args){const {data,error}=await supabase.rpc(name,args);if(error)throw error;return data}
async function createRoom(){const game=document.querySelector('#room-game').value;const max=Number(document.querySelector('#room-max').value);const auctionCount=game==='auction'?Number(document.querySelector('#room-auction-count').value):null;if(supabase){const data=await rpc('create_room',{p_game_type:game,p_max_players:max,p_settings:{auctionCount}});await open(data.room_id)}else{localCreate(game,max,{auctionCount})}window.__MA.state.view='room';window.__MA.render();toast('Room created','good')}
async function joinRoom(){const code=document.querySelector('#room-code').value.trim().toUpperCase();if(!/^[A-Z0-9]{6}$/.test(code)){toast('Room code must be 6 characters.','error');return}if(!supabase){toast('Offline demo rooms only exist on this browser.','error');return}const data=await rpc('join_room',{p_code:code});await open(data.room_id);window.__MA.state.view='room';window.__MA.render();toast('Joined room','good')}
async function leave(){if(s.local){s={id:null,room:null,players:[],channel:null,local:false};window.__MA.render();return}if(s.id)await rpc('leave_room',{p_room_id:s.id});if(s.channel)unsubscribeRoom(s.channel);s={id:null,room:null,players:[],channel:null,local:false};window.__MA.render()}
async function ready(){const mine=currentMe();if(!mine)return;if(s.local){mine.ready=!mine.ready}else await rpc('set_room_ready',{p_room_id:s.id,p_ready:!mine.ready});await load();window.__MA.render()}
async function start(){const allReady=s.players.length===s.room.max_players&&s.players.every(p=>p.ready);if(!allReady){toast('Everyone must be ready.','error');return}if(s.local){s.room.status='playing';s.room.game_state=startState(s.room.game_type,s.players.length,s.room.settings)}else await rpc('start_room',{p_room_id:s.id});await load();if(s.room.game_type==='auction'&&!s.local&&s.room.game_state.phase==='started'){if(s.room.host_id===me())await setState(startState('auction',s.players.length,s.room.settings))}else if(s.room.game_type==='lebes'&&!s.local&&s.room.game_state.phase==='started'&&s.room.host_id===me())await setState(startState('lebes',s.players.length,s.room.settings));window.__MA.render()}
async function setState(next){if(s.local){s.room.game_state=next;return}await rpc('set_room_game_state',{p_room_id:s.id,p_game_state:next});await load()}
async function runFifa(){if(s.room.game_type==='fifa'){if(!s.local){const {error}=await supabase.functions.invoke('simulate-match',{body:{room_id:s.id,game_type:'fifa'}});if(error)throw error}else{s.room.game_state={phase:'result',result:buildResult(s.players.map(p=>({name:p.username,players:PLAYERS.slice().sort(()=>Math.random()-.5).slice(0,7)})))}}await load();window.__MA.render()}}
function buildResult(teams){const r=runMatchSimulation(teams);return {scoreline:r.scoreline,winner:r.winner?.name||'DRAW',motm:r.motm?.name||'Unknown',events:r.events}}
async function auctionBid(){const mep=currentMe();if(!mep)return;const gs=s.room.game_state,lot=gs.players?.[gs.currentIndex];if(!lot)return;const amount=(gs.highestSeat==null?lot.startBid:gs.currentBid+500000);if(s.local){if(amount>(gs.teams[mep.seat]?.budget||0)){toast('Not enough budget','error');return}const next=clone(gs);next.currentBid=amount;next.highestSeat=mep.seat;s.room.game_state=next;await load();window.__MA.render();return}await rpc('place_auction_bid',{p_room_id:s.id,p_lot_index:gs.currentIndex,p_amount:amount});await load();window.__MA.render()}
async function closeLot(){const gs=s.room.game_state;if(s.local){const idx=gs.currentIndex,lot=gs.players[idx];if(!lot)return;const next=clone(gs),seat=next.highestSeat;if(seat!==null){const amount=next.currentBid;next.teams[seat].budget-=amount;next.teams[seat].players.push({...lot,paidPrice:amount,compensation:false});next.lastWinner={seat,player:lot,amount};if(idx===0&&next.teams.length===2){const loser=seat===0?1:0;const candidates=next.players.filter((p,i)=>i!==idx&&!p.removedFromAuction&&!next.teams.some(t=>t.players.some(x=>x.id===p.id)));const comp=candidates.length?pick(candidates):null;if(comp){const value=Math.floor(amount/2);comp.removedFromAuction=true;const free={...comp,paidPrice:0,compensation:true,compensationValue:value};next.teams[loser].players.push(free);next.lastCompensation={seat:loser,player:free,value,sourceLot:0}}}}let n=idx+1;while(n<next.players.length&&next.players[n].removedFromAuction)n++;next.currentIndex=n;next.currentBid=next.players[n]?.startBid||0;next.highestSeat=null;next.phase=n>=next.players.length?'complete':'auction';s.room.game_state=next;window.__MA.render();return}await rpc('close_auction_lot',{p_room_id:s.id,p_lot_index:gs.currentIndex});await load();window.__MA.render()}
async function runAuctionMatch(){const gs=s.room.game_state;if(!gs||gs.phase!=='complete'){toast('Complete the auction first.','error');return}if(s.local){const teams=gs.teams.map((t,i)=>({name:s.players[i]?.username||`TEAM ${i+1}`,players:t.players}));s.room.game_state={...gs,phase:'result',result:buildResult(teams)};window.__MA.render();return}const {error}=await supabase.functions.invoke('simulate-match',{body:{room_id:s.id,game_type:'auction'}});if(error)throw error;await load();window.__MA.render()}
function chooseBox(i){const gs=s.room.game_state,m=currentMe();if(m?.seat!==gs.turnSeat)return;const b=gs.boxes?.find(x=>x.i===i);if(!b)return;const p=PLAYERS.find(x=>x.id===b.playerId)||PLAYERS[0];const next=clone(gs);next.cards[m.seat]=next.cards[m.seat]||[];next.cards[m.seat].push(p);next.turnSeat=(m.seat+1)%s.players.length;next.boxes=Array.from({length:6},(_,n)=>({i:n,playerId:pick(PLAYERS).id}));if(s.local){s.room.game_state=next;window.__MA.render()}else setState(next).then(()=>window.__MA.render()).catch(e=>toast(e.message,'error'))}
function finishedHtml(){const r=s.room.game_state?.result||{};return `<div class="result"><div><div class="kicker">FINAL RESULT</div><div class="result-score">${esc(r.scoreline||'—')}</div><div class="result-winner">${esc(r.winner||'DRAW')}</div><div class="motm" style="margin-top:10px">MOTM · ${esc(r.motm||'—')}</div></div></div>`}
function lobbyHtml(){const r=s.room,mine=currentMe(),allReady=s.players.length===r.max_players&&s.players.every(p=>p.ready);return `<div class="section-head"><div><div class="kicker">ROOM / ${esc(r.code)}</div><h2 class="page-title">${r.game_type==='fifa'?'FIFA Game':r.game_type==='auction'?'Auction':'Lebes Sahbak'}</h2><div class="muted">${s.players.length}/${r.max_players} connected</div></div><button class="danger" data-room="leave">LEAVE</button></div><div class="panel"><div class="room-code">${esc(r.code)}</div><div class="muted" style="margin-top:7px">Share this code with the other players.</div><div class="room-seats">${Array.from({length:r.max_players},(_,i)=>{const p=s.players[i];return `<div class="room-seat ${p?'filled':''}"><div><div class="kicker">TEAM ${i+1}</div><strong>${p?esc(p.username):'Waiting…'}</strong></div><div class="${p?.ready?'ready':'waiting'}"><span class="status-dot"></span>${p?.ready?'READY':'NOT READY'}</div></div>`}).join('')}</div><div class="room-actions"><button class="secondary" data-room="ready">${mine?.ready?'UNREADY':'READY'}</button>${r.host_id===me()?`<button class="primary" data-room="start" ${allReady?'':'disabled'}>START GAME</button>`:''}</div></div>`}
function auctionHtml(){const gs=s.room.game_state,meP=currentMe(),idx=meP?.seat??0,lot=gs.players?.[gs.currentIndex],team=gs.teams?.[idx]||{budget:gs.budget,players:[]};if(gs.phase==='result')return finishedHtml();if(gs.phase==='complete')return `<div class="section-head"><div><div class="kicker">ONLINE AUCTION / ${esc(s.room.code)}</div><h2 class="page-title">Auction closed</h2><div class="muted">Every team can review its squad before the host starts the AI match.</div></div><button class="danger" data-room="leave">LEAVE</button></div><div class="two">${gs.teams.map((t,i)=>`<div class="team-box"><div class="team-head"><strong>TEAM ${i+1} · ${esc(s.players[i]?.username||'Player')}</strong><span class="money">${money(t.budget)}</span></div><div class="list" style="margin-top:9px">${(t.players||[]).map(p=>`<div class="list-item"><span>${esc(p.name)} ${p.compensation?'<small>FREE</small>':''}</span><b>${p.compensation?money(p.compensationValue):money(p.paidPrice)}</b></div>`).join('')}</div></div>`).join('')}</div><button class="primary" data-room="auction-match" style="margin-top:15px" ${s.room.host_id===me()?'':'disabled'}>RUN AI MATCH</button>`;return `<div class="section-head"><div><div class="kicker">ONLINE AUCTION / ${esc(s.room.code)}</div><h2 class="page-title">Live bidding</h2><div class="muted">Team ${idx+1} · ${money(team.budget)}</div></div><button class="danger" data-room="leave">LEAVE</button></div><div class="two"><div class="panel">${lot?`<div class="split"><span class="pill">LOT ${gs.currentIndex+1}/${gs.players.length}</span><span class="money">${money(gs.currentBid)}</span></div><div class="auction-player" style="margin-top:12px"><div class="auction-rating">${lot.rating}</div><div><div class="kicker">${esc(lot.pos)} · ${esc(lot.team)}</div><h2 style="margin:8px 0">${esc(lot.name)}</h2><div class="muted">Leader · ${gs.highestSeat===null?'—':'TEAM '+(gs.highestSeat+1)}</div><div class="bid-row" style="margin-top:13px"><button class="bid-btn a" data-room="bid">BID + 500K</button></div>${gs.lastCompensation?`<div class="notice warn" style="margin-top:10px">TEAM ${gs.lastCompensation.seat+1} received <b>${esc(gs.lastCompensation.player.name)}</b> free · recorded value ${money(gs.lastCompensation.value)}.</div>`:''}${s.room.host_id===me()?'<button class="primary" data-room="close-lot" style="margin-top:10px;width:100%">CLOSE LOT</button>':''}</div></div>`:'Auction complete.'}</div><div class="panel"><div class="kicker">YOUR SQUAD</div><div class="list" style="margin-top:10px">${team.players.length?team.players.map(p=>`<div class="list-item"><span>${esc(p.name)} ${p.compensation?'<small>FREE</small>':''}</span><b>${p.rating}</b></div>`).join(''):'<div class="empty">No players yet.</div>'}</div><div class="kicker" style="margin-top:20px">ALL BUDGETS</div><div class="list" style="margin-top:9px">${gs.teams.map((t,i)=>`<div class="list-item"><span>TEAM ${i+1}</span><b>${money(t.budget)}</b></div>`).join('')}</div></div></div>`}
function lebesHtml(){const gs=s.room.game_state,m=currentMe(),pickSeat=gs.turnSeat;return `<div class="section-head"><div><div class="kicker">ONLINE LEBES / ${esc(s.room.code)}</div><h2 class="page-title">Pick the box.</h2><div class="muted">Current picker · <b>TEAM ${pickSeat+1} · ${esc(s.players[pickSeat]?.username||'Player')}</b></div></div><button class="danger" data-room="leave">LEAVE</button></div><div class="two"><div class="panel"><div class="three">${gs.boxes.map(b=>`<button class="game-card" data-box-online="${b.i}" ${m?.seat!==pickSeat?'disabled':''}><div class="index">BOX ${b.i+1}</div><div class="game-mark" style="margin-top:28px">?</div><h3 style="font-size:20px;margin-top:16px">Mystery</h3><div class="muted">${m?.seat===pickSeat?'Choose':'Waiting'}</div></button>`).join('')}</div></div><div class="panel"><div class="kicker">COLLECTIONS</div><div class="list" style="margin-top:10px">${s.players.map((p,i)=>`<div class="team-box"><div class="team-head"><strong>TEAM ${i+1} · ${esc(p.username)}</strong><span class="pill">${(gs.cards?.[i]||[]).length}</span></div>${(gs.cards?.[i]||[]).map(x=>`<div class="list-item" style="margin-top:7px"><span>${esc(x.name)}</span><b>${x.rating}</b></div>`).join('')}</div>`).join('')}</div></div></div>`}
function gameHtml(){const g=s.room.game_type; if(g==='auction')return auctionHtml(); if(g==='lebes')return lebesHtml(); const gs=s.room.game_state||{};return gs.result?finishedHtml():`<div class="section-head"><div><div class="kicker">ONLINE FIFA / ${esc(s.room.code)}</div><h2 class="page-title">Shared match center</h2><div class="muted">The host starts one server-side simulation so every device sees the same result.</div></div><button class="danger" data-room="leave">LEAVE</button></div><div class="panel"><button class="primary" data-room="run-fifa" ${s.room.host_id===me()?'':'disabled'}>RUN AI MATCH</button></div>`}
export const ROOMS={render(){if(s.id&&s.room){return s.room.status==='lobby'?lobbyHtml():gameHtml()}return `<div class="section-head"><div><div class="kicker">ONLINE CENTER</div><h2 class="page-title">Open a room.</h2><div class="muted">Cross-device realtime needs Supabase. Offline play is available inside the games themselves.</div></div><span class="pill live">ONLINE + OFFLINE</span></div><div class="two"><div class="panel"><div class="field"><label>Game</label><select id="room-game"><option value="fifa">FIFA Game</option><option value="auction">Auction</option><option value="lebes">Lebes Sahbak</option></select></div><div class="field"><label>Players</label><select id="room-max"><option value="2">2 players</option><option value="3">3 players</option><option value="4">4 players</option></select></div><div class="field"><label>Auction roster</label><select id="room-auction-count"><option value="5">5 players · €100M</option><option value="11">11 players · €250M</option></select></div><button class="primary" data-room="create">CREATE ROOM</button></div><div class="panel"><div class="field"><label>Room code</label><input id="room-code" maxlength="6" placeholder="AB12CD" autocapitalize="characters"></div><button class="secondary" data-room="join">JOIN ROOM</button>${supabase?'':'<div class="notice warn" style="margin-top:12px">Supabase is not connected. Join/create buttons will not create cross-device rooms until you add your project values.</div>'}</div></div>`},bind(){document.querySelectorAll('[data-room]').forEach(b=>b.addEventListener('click',async()=>{try{const a=b.dataset.room;if(a==='create')await createRoom();if(a==='join')await joinRoom();if(a==='leave')await leave();if(a==='ready')await ready();if(a==='start')await start();if(a==='run-fifa')await runFifa();if(a==='bid')await auctionBid();if(a==='close-lot')await closeLot();if(a==='auction-match')await runAuctionMatch()}catch(e){toast(e.message||'Room error','error')}}));document.querySelectorAll('[data-box-online]').forEach(b=>b.addEventListener('click',()=>chooseBox(Number(b.dataset.boxOnline))))},reset(){if(s.channel)unsubscribeRoom(s.channel);s={id:null,room:null,players:[],channel:null,local:false}}};
