import { PLAYERS } from '../../data/players.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let state={phase:'setup',players:['Player A','Player B'],turn:0,boxes:[],cards:[[],[]],revealed:null};
function newRound(){state.phase='choose';state.revealed=null;state.boxes=PLAYERS.slice().sort(()=>Math.random()-.5).slice(0,6).map((p,i)=>({i,player:p}));}
function start(){state.players=[document.querySelector('#lebes-a')?.value.trim()||'Player A',document.querySelector('#lebes-b')?.value.trim()||'Player B'];state.cards=[[],[]];state.turn=0;newRound();window.__MA.render()}
function choose(i){if(state.phase!=='choose')return;const box=state.boxes.find(x=>x.i===i);if(!box)return;state.revealed=box.player;state.cards[state.turn].push(box.player);state.phase='revealed';window.__MA.render()}
function next(){state.turn=state.turn===0?1:0;newRound();window.__MA.render()}
function card(p){return `<div class="player-card ${esc(p.rarity||'silver')}"><div class="rarity-tag">${esc((p.rarity||'silver').toUpperCase())}</div><div class="player-rating">${p.rating}</div><div class="player-position">${esc(p.pos)}</div><div class="player-name">${esc(p.name)}</div><div class="player-team">${esc(p.team)}</div></div>`}
export const LEBES={render(){if(state.phase==='setup')return `<div class="section-head"><div><div class="kicker">03 / LEBES SAHBAK</div><h2 class="page-title">Pick a box for your friend.</h2><div class="muted">The card belongs to the player who picks the box — not the player who receives the choice.</div></div></div><div class="two"><div class="panel"><div class="field"><label>Player A</label><input id="lebes-a" value="Player A" maxlength="18"></div><div class="field"><label>Player B</label><input id="lebes-b" value="Player B" maxlength="18"></div><button class="primary" data-lebes="start">START LOCAL GAME</button></div><div class="panel"><div class="notice warn"><b>House rule</b><br>Every round, one player chooses a box. Whatever card is inside is added to that same player's collection.</div></div></div>`;const picker=state.players[state.turn];return `<div class="section-head"><div><div class="kicker">03 / LEBES SAHBAK</div><h2 class="page-title">${state.phase==='choose'?'Choose your box':'Card found'}</h2><div class="muted">Current picker · <b>${esc(picker)}</b></div></div><button class="secondary" data-lebes="reset">New game</button></div><div class="two"><div class="panel"><div class="three">${state.boxes.map(b=>`<button class="game-card" data-box="${b.i}" ${state.phase!=='choose'?'disabled':''}><div class="index">BOX ${b.i+1}</div><div class="game-mark" style="margin-top:28px">?</div><h3 style="font-size:20px;margin-top:16px">Mystery</h3><div class="muted">${state.phase==='choose'?'Take your pick':'Round locked'}</div></button>`).join('')}</div></div><div class="panel">${state.revealed?`${card(state.revealed)}<div class="notice good" style="margin-top:10px"><b>${esc(state.revealed.name)}</b> goes to <b>${esc(picker)}</b>.</div><button class="primary" data-lebes="next" style="margin-top:12px;width:100%">NEXT TURN</button>`:`<div class="empty">Choose one of the boxes. The reveal happens here.</div>`}</div></div><div class="section-head"><div><div class="kicker">COLLECTIONS</div><h2>Round cards</h2></div></div><div class="two">${state.players.map((name,i)=>`<div class="panel"><div class="split"><h3>${esc(name)}</h3><span class="pill">${state.cards[i].length} cards</span></div><div class="list" style="margin-top:10px">${state.cards[i].length?state.cards[i].map(p=>`<div class="list-item"><span>${esc(p.name)}</span><b>${p.rating}</b></div>`).join(''):'<div class="empty">No cards yet.</div>'}</div></div>`).join('')}</div>`},bind(){document.querySelectorAll('[data-lebes]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.lebes;if(a==='start')start();if(a==='reset'){state={phase:'setup',players:['Player A','Player B'],turn:0,boxes:[],cards:[[],[]],revealed:null};window.__MA.render()}if(a==='next')next()}));document.querySelectorAll('[data-box]').forEach(b=>b.addEventListener('click',()=>choose(Number(b.dataset.box))))}};
