import { PLAYERS } from '../../data/players.js';
import { runMatchSimulation } from '../../js/engine.js';

const KEY='mind_arena_fifa_collection_v3';
const starter=['p006','p007','p013','p016','p020'];
let state={team:load(),lastCard:null,mode:'offline',result:null};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function load(){try{const v=JSON.parse(localStorage.getItem(KEY));return Array.isArray(v)?v:starter.slice()}catch{return starter.slice()}}
function save(){localStorage.setItem(KEY,JSON.stringify(state.team))}
function roster(){return state.team.map(id=>PLAYERS.find(p=>p.id===id)).filter(Boolean)}
function drawPack(){
  const order=['blandor','prime','gold','silver']; const r=Math.random(); const rarity=r<.06?order[0]:r<.24?order[1]:r<.64?order[2]:order[3];
  const pool=PLAYERS.filter(p=>p.rarity===rarity || (rarity==='silver' && !p.rarity));
  const p=pool[Math.floor(Math.random()*pool.length)]||PLAYERS[0]; state.lastCard=p; if(!state.team.includes(p.id))state.team.push(p.id); save(); return p;
}
function card(p){return `<div class="player-card ${esc(p.rarity||'silver')}"><div class="rarity-tag">${esc((p.rarity||'silver').toUpperCase())}</div><div class="player-rating">${p.rating}</div><div class="player-position">${esc(p.pos)}</div><div class="player-name">${esc(p.name)}</div><div class="player-team">${esc(p.team)}</div><div class="player-meta"><span class="meta-pill">${p.id}</span><span class="meta-pill">CARD</span></div></div>`}
function simulate(){const mine=roster(); const opp=PLAYERS.slice().sort(()=>Math.random()-.5).slice(0,Math.max(5,mine.length)); state.result=runMatchSimulation([{name:'YOUR XI',players:mine},{name:'CPU XI',players:opp}]); const r=state.result; window.__MA.toast('Match finished','good'); renderResult();}
function renderResult(){const box=document.querySelector('#fifa-result'); if(!box||!state.result)return; const r=state.result; box.innerHTML=`<div class="kicker">FULL TIME</div><div class="result-score">${r.scoreline}</div><div class="result-winner">${r.winner?esc(r.winner.name):'DRAW'}</div><div class="motm" style="margin-top:10px">MOTM · ${esc(r.motm.name)}</div><div class="match-feed" style="margin-top:18px">${r.events.slice(-6).map(e=>`<div class="match-event"><strong>${e.minute}' · ${esc(e.team)}${e.goal?' · GOAL':''}</strong>${esc(e.text)}</div>`).join('')}</div>`}
export const FIFA={
 render(){const list=roster();return `<div class="section-head"><div><div class="kicker">01 / FIFA GAME</div><h2 class="page-title">Card Lab</h2><div class="muted">Your collection lives on this device until a saved-account wallet is connected.</div></div><div class="toolbar"><button class="secondary" data-fifa="reset">Reset</button><button class="primary" data-fifa="pack">Deal card</button></div></div><div class="two"><div class="panel"><div class="split"><div><div class="kicker">COLLECTION</div><h3>My cards</h3></div><span class="pill">${list.length} owned</span></div><div class="card-grid" style="margin-top:12px">${list.map(card).join('')}</div></div><div><div class="pack-stage"><div class="pack-glow"></div><div class="pack-card"><span>MIND<br>PACK</span></div><div style="position:absolute;bottom:20px"><button class="primary" data-fifa="pack">DEAL THE NEXT CARD</button></div></div>${state.lastCard?`<div class="notice good" style="margin-top:11px">Last card: <b>${esc(state.lastCard.name)}</b> · ${state.lastCard.rating}</div>`:''}</div></div><div class="section-head"><div><div class="kicker">QUICK MATCH</div><h2>One-screen AI match</h2></div><span class="pill">OFFLINE</span></div><div class="three"><div class="panel"><div class="kicker">YOUR RATING</div><div class="big-number">${Math.round(list.reduce((a,p)=>a+p.rating,0)/Math.max(1,list.length))}</div><div class="muted">Average card rating</div><button class="primary" data-fifa="match" style="margin-top:15px;width:100%">SIMULATE MATCH</button></div><div class="panel"><h3>Rules</h3><div class="list"><div class="list-item"><span>Squad size</span><b>5+ cards</b></div><div class="list-item"><span>Best card</span><b>Blandor</b></div><div class="list-item"><span>Result</span><b>AI simulation</b></div></div></div><div id="fifa-result" class="panel"><div class="kicker">MATCH CENTER</div><h3>No match yet</h3><div class="muted">Run a match and the play-by-play will appear here.</div></div></div>`},
 bind(){document.querySelectorAll('[data-fifa]').forEach(btn=>btn.addEventListener('click',()=>{const a=btn.dataset.fifa;if(a==='pack'){drawPack();window.__MA.toast('Card added','good');window.__MA.render()}else if(a==='reset'){state.team=starter.slice();state.lastCard=null;state.result=null;save();window.__MA.toast('Collection reset');window.__MA.render()}else if(a==='match')simulate()}));}
};
