import { PLAYERS, COACHES } from '../../data/players.js';
import { money, runMatchSimulation, pick } from '../../js/engine.js';
import { supabase } from '../../js/supabase.js';

let state=blank();
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const budgetFor=count=>count===11?250000000:100000000;
function blank(){return {mode:'offline',count:5,budget:100000000,teams:[{name:'TEAM A',budget:100000000,players:[],coach:null},{name:'TEAM B',budget:100000000,players:[],coach:null}],players:[],currentIndex:0,currentBid:0,highestSeat:null,turnSeat:0,lastWinner:null,lastCompensation:null,complete:false,result:null,roomId:null}}
function reset(){state=blank()}
function makePool(){state.players=PLAYERS.slice().sort(()=>Math.random()-.5).slice(0,state.count).map(p=>({...p,startBid:Math.max(1000000,Math.round(((p.rating-70)*650000+Math.random()*1700000)/100000)*100000)}));state.currentIndex=0;state.currentBid=state.players[0]?.startBid||1000000;state.highestSeat=null;state.turnSeat=0;}
function activeLot(){return state.players[state.currentIndex]}
function nextLocalLot(){let n=state.currentIndex+1;while(n<state.players.length && state.players[n].reservedFor!==undefined)n++;state.currentIndex=n;state.currentBid=state.players[n]?.startBid||0;state.highestSeat=null;state.turnSeat=0;if(n>=state.players.length)state.complete=true}
function localBid(seat){if(state.complete)return; if(state.highestSeat===seat){window.__MA.toast('You already lead this lot','error');return;} const next=state.highestSeat==null?state.currentBid:state.currentBid+500000; if(next>state.teams[seat].budget){window.__MA.toast('Not enough budget','error');return}state.currentBid=next;state.highestSeat=seat;state.turnSeat=seat===0?1:0;}
function localClose(){const lot=activeLot();if(!lot)return; if(state.highestSeat!==null){const winner=state.highestSeat;const price=state.currentBid;state.teams[winner].budget-=price;state.teams[winner].players.push({...lot,paidPrice:price,compensation:false});state.lastWinner={seat:winner,player:lot,amount:price}; if(state.currentIndex===0 && state.teams.length===2){const loser=winner===0?1:0;const candidates=state.players.filter((p,i)=>i!==state.currentIndex && !p.reservedFor && !state.teams.some(t=>t.players.some(x=>x.id===p.id)));const comp=candidates.length?pick(candidates):null;if(comp){comp.reservedFor=loser;const free={...comp,paidPrice:0,compensation:true,compensationValue:Math.floor(price/2)};state.teams[loser].players.push(free);state.lastCompensation={seat:loser,player:free,value:Math.floor(price/2)};}}}else state.lastWinner=null; nextLocalLot();}
function startLocal(){state.mode='offline';state.count=Number(document.querySelector('#auction-count')?.value||5);state.budget=budgetFor(state.count);state.teams=[{name:'TEAM A',budget:state.budget,players:[],coach:null},{name:'TEAM B',budget:state.budget,players:[],coach:null}];state.result=null;state.complete=false;makePool();window.__MA.render()}
function playLocalMatch(){if(!state.complete){window.__MA.toast('Finish the auction first','error');return}for(const t of state.teams){if(!t.players.length){window.__MA.toast('Both teams need players','error');return}}const teams=state.teams.map(t=>({name:t.name,players:t.players,coachRating:t.coach?.rating||0}));state.result=runMatchSimulation(teams);window.__MA.render()}
function teamHtml(team,i){return `<div class="team-box ${state.highestSeat===i?'active':''}"><div class="team-head"><strong>${esc(team.name)}</strong><span class="money">${money(team.budget)}</span></div><div class="list" style="margin-top:9px">${team.players.length?team.players.map(p=>`<div class="list-item"><span>${esc(p.name)} ${p.compensation?'<small>FREE</small>':''}</span><b>${p.compensation?money(p.compensationValue):money(p.paidPrice||0)}</b></div>`).join(''):'<div class="empty">No player yet.</div>'}</div><select class="field" data-coach="${i}" style="margin-top:10px"><option value="">Choose coach</option>${COACHES.map(c=>`<option value="${c.id}" ${team.coach?.id===c.id?'selected':''}>${esc(c.name)} · ${c.rating}</option>`).join('')}</select></div>`}
function resultHtml(){const r=state.result;if(!r)return '';return `<div class="result"><div><div class="kicker">AI MATCH</div><div class="result-score">${r.scoreline}</div><div class="result-winner">${r.winner?esc(r.winner.name):'DRAW'}</div><div class="motm" style="margin-top:10px">MOTM · ${esc(r.motm.name)}</div></div></div>`}
export const AUCTION={
 render(){
   if(!state.players.length)return `<div class="section-head"><div><div class="kicker">02 / AUCTION</div><h2 class="page-title">Build a team from the table.</h2><div class="muted">Virtual game credits only. Two teams share the offline screen. Online rooms use the same rules.</div></div></div><div class="panel"><div class="three"><div class="panel" style="background:#0d1016"><div class="kicker">ROSTER</div><h3>5 players</h3><div class="big-number">€100M</div><div class="muted">starting budget per team</div></div><div class="panel" style="background:#0d1016"><div class="kicker">ROSTER</div><h3>11 players</h3><div class="big-number">€250M</div><div class="muted">starting budget per team</div></div><div class="panel" style="background:#0d1016"><div class="kicker">SPECIAL RULE</div><h3>First lot only</h3><div class="muted">After the first winning bid in a two-team auction, the other team receives one random free player with a recorded value equal to half the winning bid.</div></div></div><div class="toolbar" style="margin-top:16px"><select id="auction-count" class="field" style="width:auto"><option value="5">5 players · €100M</option><option value="11">11 players · €250M</option></select><button class="primary" data-auction="start">START OFFLINE AUCTION</button></div></div>`;
   const p=activeLot(); const complete=state.complete; return `<div class="section-head"><div><div class="kicker">02 / AUCTION · ${state.mode.toUpperCase()}</div><h2 class="page-title">Live table</h2><div class="muted">${complete?'The table is closed. Finish with an AI match.':`Lot ${state.currentIndex+1} of ${state.players.length}`}</div></div><div class="toolbar"><button class="secondary" data-auction="new">New auction</button>${complete?'<button class="primary" data-auction="match">PLAY AI MATCH</button>':''}</div></div>${!complete&&p?`<div class="two"><div class="panel"><div class="split"><span class="pill">LOT ${state.currentIndex+1}/${state.players.length}</span><span class="money">Current · ${money(state.currentBid)}</span></div><div class="auction-player" style="margin-top:12px"><div class="auction-rating">${p.rating}</div><div><div class="kicker">${esc(p.pos)} · ${esc(p.team)}</div><h2 style="margin:8px 0">${esc(p.name)}</h2><div class="muted">Starting bid · ${money(p.startBid)}</div><div class="lot-track"><i style="width:${Math.min(100,15+(state.currentBid/Math.max(p.startBid*3,1))*20)}%"></i></div><div class="bid-row" style="margin-top:13px"><button class="bid-btn a" data-auction="bidA">TEAM A · BID</button><button class="bid-btn b" data-auction="bidB">TEAM B · BID</button></div><div class="notice" style="margin-top:10px">${state.highestSeat===null?'No one is leading yet.':'Team '+(state.highestSeat+1)+' is leading.'}</div><button class="primary" data-auction="sold" style="width:100%;margin-top:10px">CLOSE LOT</button></div></div>${state.lastWinner?`<div class="notice good" style="margin-top:10px">${esc(state.lastWinner.player.name)} sold to Team ${state.lastWinner.seat+1} for <b>${money(state.lastWinner.amount)}</b>.</div>`:''}${state.lastCompensation?`<div class="notice warn" style="margin-top:9px">Team ${state.lastCompensation.seat+1} gets <b>${esc(state.lastCompensation.player.name)}</b> free. Recorded value: <b>${money(state.lastCompensation.value)}</b> (half the winning bid).</div>`:''}</div><div class="panel"><div class="kicker">SQUADS</div><div class="list" style="margin-top:9px">${state.teams.map(teamHtml).join('')}</div></div></div>`:`${state.complete?resultHtml():''}${state.complete&&!state.result?`<div class="two">${state.teams.map(teamHtml).join('')}</div>`:''}`}
 ,
 bind(){document.querySelectorAll('[data-auction]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.auction;if(a==='start')startLocal();else if(a==='new'){reset();window.__MA.render()}else if(a==='bidA')localBid(0),window.__MA.render();else if(a==='bidB')localBid(1),window.__MA.render();else if(a==='sold')localClose(),window.__MA.render();else if(a==='match')playLocalMatch()}));document.querySelectorAll('[data-coach]').forEach(sel=>sel.addEventListener('change',()=>{const i=Number(sel.dataset.coach);state.teams[i].coach=COACHES.find(c=>c.id===sel.value)||null;}));}
};
